# ========================================================================
# App Engine Configuration.
# Full reference is available at:
# https://cloud.google.com/appengine/docs/standard/java11/config/appref
# ========================================================================

runtime: java8
instance_class: F2
service: default
handlers:
- url: /(.*)
  script: auto
  secure: always
automatic_scaling:
  min_instances: 1
  max_instances: 1
entrypoint: java -Dthin.root=. -war twenty-one-points-0.0.1-SNAPSHOT.war
skip_files:
- node_modules/
- node/
- build/
- target/
- test/
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(src/test/.*)
- ^(target/.*)
- ^(build/.*)
- ^(node/.*)
- ^(node_modules/.*)

